DB access for Runner Test 1

diff --git a/.github/workflows/prod-backend-build-docker-push-image-deploy-database.yml b/.github/workflows/prod-backend-build-docker-push-image-deploy-database.yml
--- a/.github/workflows/prod-backend-build-docker-push-image-deploy-database.yml
+++ b/.github/workflows/prod-backend-build-docker-push-image-deploy-database.yml
@@ -82,30 +82,30 @@ jobs:
 
       - name: Start Cloud SQL Auth Proxy
         run: |
-          ./cloud-sql-proxy "$CONNECTION_NAME" --port 3306 > proxy.log 2>&1 & sleep 5
+          ./cloud-sql-proxy --private-ip "$CONNECTION_NAME" --address 127.0.0.1 --port 3306 > proxy.log 2>&1 & sleep 5
 
-      # - name: Check if MySQL is listening
-      #   run: |
-      #     sudo apt-get update
-      #     sudo apt install -y netcat-openbsd
-      #     nc -zv 127.0.0.1 3306 || echo "Port 3306 is not open"
+      - name: Check if MySQL is listening
+        run: |
+          sudo apt-get update
+          sudo apt install -y netcat-openbsd
+          nc -zv 127.0.0.1 3306 || echo "Port 3306 is not open"
 
       - name: Print Proxy Logs
         run: cat proxy.log
     
-      # - name: Apply schema to Cloud SQL (MySQL)
-      #   run: |
-      #     mysql -u"$DB_USER" -p"$DB_PASSWORD" -h 127.0.0.1 -P 3306 "$DB_NAME" < schema.sql 2> error.log || {
-      #     if grep -q "ERROR 1050" error.log; then
-      #       echo "Database $DB_NAME already exists. Continuing..."
-      #       cat error.log
-      #       exit 0
-      #     else
-      #       echo "An error occurred while applying the schema:"
-      #       cat error.log
-      #       exit 1
-      #     fi
-      #     }
+      - name: Apply schema to Cloud SQL (MySQL)
+        run: |
+          mysql -u"$DB_USER" -p"$DB_PASSWORD" -h 127.0.0.1 -P 3306 "$DB_NAME" < schema.sql 2> error.log || {
+          if grep -q "ERROR 1050" error.log; then
+            echo "Database $DB_NAME already exists. Continuing..."
+            cat error.log
+            exit 0
+          else
+            echo "An error occurred while applying the schema:"
+            cat error.log
+            exit 1
+          fi
+          }
 
 
 
